server:
  port: 8080

spring:
  kafka:
    bootstrap-servers:
      - 8.142.25.102:9092
#    bootstrap-servers: 192.168.186.200:9092
    # producer要求kafka集群的leader在考虑完成请求之前收到的确认数, 用于控制发送记录在kafka服务端的持久化
    # acks = 0 生产者不会等待来自kafka服务端的任何确认, 该记录将立即添加到套接字缓冲区, 并视为已发送
    #           这种情况下, 无法保证kafka服务端收到记录
    # acks = 1 kafka集群的leader会将记录写入其本地日志, 无需等待所有kafka副本服务端的完全确认即可回应, 这种情况下
    #           这种情况下, 如果leader在确认记录后立即失败, 但在将数据复制到所有kafka副本服务器之前, 记录会丢失
    # acks = all 这意味着kafka集群的leader将会等待所有kafka集群副本服务器确认记录, 只要集群中有一个kafka服务器存活, 记录就不会丢失
    producer:
      acks: all
      retries: 3
      # bytes = 16KB
      batch-size: 16384
      # bytes = 32MB
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 10
    consumer:
      enable-auto-commit: true
      properties:
        session.timeout.ms: 6000
        heartbeat.interval.ms: 2000
        mas.pool.interval.ms: 20000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: test_group
